

import { Language, UIStrings, ExampleCategory, HistoricalDataPoint } from './types';

export const GEMINI_MODEL_TEXT = 'gemini-2.5-flash';
export const GEMINI_MODEL_VISION = 'gemini-2.5-flash';

export const karnatakaDistricts = [
    { name: 'Bagalkote', lat: 16.18, lon: 75.7 },
    { name: 'Ballari (Bellary)', lat: 15.15, lon: 76.92 },
    { name: 'Belagavi (Belgaum)', lat: 15.85, lon: 74.5 },
    { name: 'Bengaluru (Bangalore) Rural', lat: 13.15, lon: 77.58 },
    { name: 'Bengaluru (Bangalore) Urban', lat: 12.97, lon: 77.59 },
    { name: 'Bidar', lat: 17.91, lon: 77.52 },
    { name: 'Chamarajanagara', lat: 11.92, lon: 76.94 },
    { name: 'Chikkaballapura', lat: 13.43, lon: 77.73 },
    { name: 'Chikkamagaluru', lat: 13.32, lon: 75.77 },
    { name: 'Chitradurga', lat: 14.23, lon: 76.4 },
    { name: 'Dakshina Kannada', lat: 12.87, lon: 75.24 },
    { name: 'Davanagere', lat: 14.47, lon: 75.92 },
    { name: 'Dharwad', lat: 15.46, lon: 75.01 },
    { name: 'Gadag', lat: 15.43, lon: 75.62 },
    { name: 'Hassan', lat: 13.01, lon: 76.1 },
    { name: 'Haveri', lat: 14.8, lon: 75.4 },
    { name: 'Kalaburagi (Gulbarga)', lat: 17.33, lon: 76.83 },
    { name: 'Kodagu', lat: 12.42, lon: 75.74 },
    { name: 'Kolar', lat: 13.13, lon: 78.13 },
    { name: 'Koppal', lat: 15.35, lon: 76.15 },
    { name: 'Mandya', lat: 12.52, lon: 76.9 },
    { name: 'Mysuru (Mysore)', lat: 12.3, lon: 76.65 },
    { name: 'Raichur', lat: 16.2, lon: 77.37 },
    { name: 'Ramanagara', lat: 12.72, lon: 77.28 },
    { name: 'Shivamogga (Shimoga)', lat: 13.93, lon: 75.57 },
    { name: 'Tumakuru (Tumkur)', lat: 13.34, lon: 77.1 },
    { name: 'Udupi', lat: 13.33, lon: 74.75 },
    { name: 'Uttara Kannada', lat: 14.8, lon: 74.67 },
    { name: 'Vijayapura (Bijapur)', lat: 16.83, lon: 75.71 },
    { name: 'Vijayanagara', lat: 15.27, lon: 76.39 },
    { name: 'Yadgir', lat: 16.77, lon: 77.14 },
];

export const historicalData: HistoricalDataPoint[] = [
    { month: 'Jan', detections: 5 },
    { month: 'Feb', detections: 8 },
    { month: 'Mar', detections: 7 },
    { month: 'Apr', detections: 12 },
    { month: 'May', detections: 15 },
    { month: 'Jun', detections: 11 },
];

export const marketCrops = [
    { name: 'Tomato' },
    { name: 'Onion' },
    { name: 'Potato' },
    { name: 'Chilli' },
    { name: 'Rice (Sona Masuri)' },
    { name: 'Tur Dal' },
    { name: 'Cotton' },
];

export const karnatakaMarkets = [
    { name: 'Bagalkote APMC' },
    { name: 'Ballari APMC' },
    { name: 'Belagavi APMC' },
    { name: 'Bengaluru Rural (Doddaballapura) APMC' },
    { name: 'Bengaluru Urban (Yeshwanthpur) APMC' },
    { name: 'Bidar APMC' },
    { name: 'Chamarajanagar APMC' },
    { name: 'Chikkaballapura APMC' },
    { name: 'Chikkamagaluru APMC' },
    { name: 'Chitradurga APMC' },
    { name: 'Dakshina Kannada (Mangaluru) APMC' },
    { name: 'Davanagere APMC' },
    { name: 'Dharwad (Hubballi-Amargol) APMC' },
    { name: 'Gadag APMC' },
    { name: 'Hassan APMC' },
    { name: 'Haveri APMC' },
    { name: 'Kalaburagi (Gulbarga) APMC' },
    { name: 'Kodagu (Madikeri) APMC' },
    { name: 'Kolar APMC' },
    { name: 'Koppal APMC' },
    { name: 'Mandya APMC' },
    { name: 'Mysuru (Bandipalya) APMC' },
    { name: 'Raichur APMC' },
    { name: 'Ramanagara APMC' },
    { name: 'Shivamogga APMC' },
    { name: 'Tumakuru APMC' },
    { name: 'Udupi APMC' },
    { name: 'Uttara Kannada (Sirsi) APMC' },
    { name: 'Vijayapura (Bijapur) APMC' },
    { name: 'Vijayanagara (Hosapete) APMC' },
    { name: 'Yadgir APMC' },
];

const enStrings = {
    landing_top_bar: "AI-powered solutions for modern agriculture.",
    landing_phone: "+91-9876543210",
    landing_email: "contact@agriverse.ai",
    landing_nav_home: "Home",
    landing_nav_about: "About",
    landing_nav_services: "Features",
    landing_nav_contact: "Contact",
    landing_hero_tagline: "The Future of Farming is Here",
    landing_hero_title: "Build Health with Technology",
    landing_hero_subtitle: "Harnessing AI to provide the best agricultural solutions for farmers across Karnataka.",
    landing_cta_dashboard: "AI Assistant",
    landing_cta_learn_more: "Learn More",
    landing_features_title: "Our Features",
    landing_features_subtitle: "We are your best partner for modern farming",
    landing_feature1_title: "Local Weather Forecast",
    landing_feature1_desc: "Get hyperlocal, real-time weather updates for your specific district in Karnataka.",
    landing_feature2_title: "AI Soil Analysis",
    landing_feature2_desc: "Get real-time crop recommendations based on your soil's health and local conditions.",
    landing_feature3_title: "Bhoomi AI Assistant",
    landing_feature3_desc: "Your bilingual AI assistant for all farming-related queries.",
    landing_feature4_title: "Plant Disease Analysis",
    landing_feature4_desc: "Upload an image of a plant to get an instant AI-powered diagnosis and treatment plan.",
    landing_feature5_title: "Agri-Marketplace",
    landing_feature5_desc: "Analyze real-time market prices, compare across markets, and get the best value for your produce.",
    why_choose_us_title: "Why Choose AgriVerseAI?",
    why_choose_us_1_title: "Data-Driven Insights",
    why_choose_us_1_desc: "Make informed decisions with precise data on soil, weather, and crop health.",
    why_choose_us_2_title: "Bilingual AI Support",
    why_choose_us_2_desc: "Get expert advice in both English and Kannada, accessible to everyone.",
    why_choose_us_3_title: "All-in-One Platform",
    why_choose_us_3_desc: "From diagnostics to market information, all the tools you need in one place.",

    appName: "AgriVerseAI",
    appDescription: "Your AI-powered agricultural partner.",
    languageEN: "English",
    languageKN: "ಕನ್ನಡ",
    cancel: "Cancel",

    assistantWelcome: "Hey there! 👋 I'm Bhoomi, your friendly AI farming companion! I'm here to help you with crops, soil health, market prices, and so much more. Think of me as your farming friend who's always ready to chat! 🌾💚",
    askWithVoice: "Ask with your voice",
    typeWithKeyboard: "Type using your keyboard",
    bilingualSupport: "Bilingual support for seamless conversations.",
    examplePromptsTitle: "What you can ask me:",
    getStarted: "Get Started",
    exampleCategories: [
        { title: "Crop Advice", prompts: [{ text: "What are the best crops to grow in red soil with high potassium?" }] },
        { title: "Disease Diagnosis", prompts: [{ text: "My tomato plant's leaves have yellow spots. What could it be?" }] },
        { title: "Market Prices", prompts: [{ text: "What is the current market price for onions in the Belagavi district?" }] },
        { title: "Scheme Information", prompts: [{ text: "Tell me about the PM-KISAN scheme." }] }
    ] as ExampleCategory[],
    messagePlaceholder: "Hi Bhoomi! I have a question... 🌱",
    send: "Send",
    voiceOutput: "Toggle Voice Output",
    cancelVoiceOutput: "Cancel Voice Output",
    errorPrefix: "Error:",
    errorApiGeneric: "Sorry, I'm having trouble connecting to my knowledge base. Please try again later.",
    errorSpeechNetwork: "Speech recognition failed due to a network issue. Please check your connection.",
    errorSpeechGeneric: "Sorry, I couldn't understand that. Please try again.",
    attachFile: "Attach File",
    agriculturalFacts: [
        "A single bushel of wheat contains about one million individual kernels.",
        "Hydroponics allows growing plants without soil, using mineral nutrient solutions in a water solvent.",
        "Bees are crucial for agriculture, pollinating approximately 80% of all flowering plants.",
        "The world's oldest living tree, Methuselah, is over 4,850 years old."
    ],
    listening: "Go ahead, I'm listening",
    weatherTitle: "Weather Wise",
    selectDistrict: "Select District",
    loadingWeather: "Loading weather...",
    weatherStatus: "Status",
    weather_high: "High",
    weather_low: "Low",
    days: ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"],
    today: "Today",
    weatherCodes: {
        0: "Clear sky", 1: "Mainly clear", 2: "Partly cloudy", 3: "Overcast",
        45: "Fog", 48: "Depositing rime fog",
        51: "Light drizzle", 53: "Moderate drizzle", 55: "Dense drizzle",
        56: "Light freezing drizzle", 57: "Dense freezing drizzle",
        61: "Slight rain", 63: "Moderate rain", 65: "Heavy rain",
        66: "Light freezing rain", 67: "Heavy freezing rain",
        71: "Slight snow fall", 73: "Moderate snow fall", 75: "Heavy snow fall",
        77: "Snow grains",
        80: "Slight rain showers", 81: "Moderate rain showers", 82: "Violent rain showers",
        85: "Slight snow showers", 86: "Heavy snow showers",
        95: "Thunderstorm", 96: "Thunderstorm with slight hail", 99: "Thunderstorm with heavy hail"
    },
    hourlyForecast: "Hourly Forecast",
    dailyForecast: "7-Day Forecast",
    airQuality: "Air Quality",
    airQualityIndex: "AQI",
    uvIndex: "UV Index",
    sunrise: "Sunrise",
    sunset: "Sunset",
    wind: "Wind",
    humidity: "Humidity",
    feelsLike: "Feels like",
    precipitation: "Precipitation",
    aqi_good: "Good",
    aqi_moderate: "Moderate",
    aqi_unhealthy_sensitive: "Unhealthy for Sensitive Groups",
    aqi_unhealthy: "Unhealthy",
    aqi_very_unhealthy: "Very Unhealthy",
    aqi_hazardous: "Hazardous",
    aqi_good_desc: "Air quality is considered satisfactory, and air pollution poses little or no risk.",
    aqi_moderate_desc: "Some pollutants may be a moderate health concern for a very small number of people.",
    aqi_unhealthy_sensitive_desc: "Members of sensitive groups may experience health effects. The general public is not likely to be affected.",
    aqi_unhealthy_desc: "Everyone may begin to experience health effects; members of sensitive groups may experience more serious health effects.",
    aqi_very_unhealthy_desc: "Health alert: everyone may experience more serious health effects.",
    aqi_hazardous_desc: "Health warnings of emergency conditions. The entire population is more likely to be affected.",

    // Soil Analysis
    soilAnalysisTitle: "Real-time Soil Analysis & Crop Prediction",
    soilAnalysisDescription: "Adjust the sliders to match your soil and climate conditions, then let our AI provide expert recommendations.",
    soilAnalysisButton: "Analyze & Predict Crops",
    soilParamTitle: "Soil & Climate Parameters",
    locationTitle: "Location",
    selectTaluk: "Select Taluk",
    selectVillage: "Select Village/Area",
    soilHealthSummary: "Soil Health Summary",
    nutrientAnalysis: "Nutrient Analysis",
    cropRecommendations: "Top Crop Recommendations",
    suitability: "Suitability",
    plantingTips: "Planting Tips",
    nitrogen: "Nitrogen (N)",
    phosphorus: "Phosphorus (P)",
    potassium: "Potassium (K)",
    ph: "pH Level",
    temperature: "Temperature",
    rainfall: "Rainfall",
    loadingAnalysis: "Analyzing your soil... this may take a moment.",
    soilHealthScoreTitle: "Soil Health Score",
    idealRange: "Ideal Range",

    // Plant Disease Analysis
    plantAnalysisTitle: "AI Plant Disease Analysis",
    plantAnalysisDescription: "Capture or upload a clear photo of an affected plant to get an instant, animated dashboard analysis.",
    uploadPlantImagePrompt: "Click to upload or drag & drop an image",
    analyzingPlant: "Analyzing your plant...",
    analysisResults: "Analysis Results Dashboard",
    diseaseName: "Disease Name",
    confidence: "Confidence",
    description: "Description",
    severity: "Severity",
    symptoms: "Symptoms",
    prevention: "Prevention",
    treatment: "Treatment",
    medicineName: "Recommended Medicine",
    usageInstructions: "Usage Instructions",
    healthyPlant: "Plant Appears Healthy",
    healthyPlantDesc: "No disease was detected in the provided image. Continue with good care practices to keep your plant thriving.",
    errorAnalysis: "Could not analyze the image. Please try again with a clearer picture.",
    analyzeAnotherPlant: "Analyze Another Plant",
    captureWithCamera: "Capture with Camera",
    or: "or",
    switchCamera: "Switch Camera",
    capture: "Capture",
    retake: "Retake",
    usePhoto: "Use Photo",
    downloadReport: "Download Report",
    readAloud: "Read Aloud",
    stopReading: "Stop Reading",
    topDetections: "Top Detections",
    affectedArea: "Affected",
    healthyArea: "Healthy",
    riskFactors: "Risk Factors",
    historicalData: "Historical Detections (Sample)",
    viewHealthDashboard: "View Regional Health Dashboard",
    backToAnalysis: "Back to Analysis",
    plantHealthDashboardTitle: "State-wide Plant Health Dashboard",
    keyMetrics: "Key Metrics",
    totalDetections: "Total Detections",
    activeAlerts: "Active Alerts",
    cropsAffected: "Crops Affected",
    diseaseSeverityIndex: "Disease Severity Index",
    diseaseTrend: "Disease Trend (12 Months)",
    detections: "Detections",
    cropDistribution: "Crop Distribution",
    diseaseDistribution: "Disease Distribution",
    environmentalCorrelation: "Environmental Correlation",
    mostAffectedDistricts: "Most Affected Districts",
    cropDiseaseHotspots: "Crop-Disease Hotspots",
    crop: "Crop",
    disease: "Disease",
    priorityAlertsTitle: "State-wide Priority Alerts",
    riskLevel: "Risk Level",
    highRisk: "High",
    moderateRisk: "Moderate",
    lowRisk: "Low",
    affectedRegions: "High-Risk Regions",
    recommendedAction: "Recommended Primary Action",

    // Marketplace
    marketplaceTitle: "Agri-Marketplace",
    marketplaceDescription: "Get real-time price analysis for your crops across major Karnataka markets.",
    selectMarket: "Select Primary Market",
    selectCrop: "Select Crop",
    analyzePrices: "Analyze Market Prices",
    priceAnalysisFor: "Price Analysis for",
    in: "in",
    minPrice: "Min Price",
    maxPrice: "Max Price",
    modalPrice: "Modal Price",
    priceTrend30Days: "Price Trend (Last 30 Days)",
    marketComparison: "Price Comparison Across Markets (per Quintal)",
    marketInsight: "AI Market Insight",
    loadingMarketAnalysis: "Analyzing market data...",
    sellYourCrop: "Sell Your Crop",
    getEstimate: "Get Price Estimate",
    quantity: "Quantity (Quintals)",
    quality: "Quality",
    estimatedValue: "Estimated Value",
    bestMarketToSell: "Best Market to Sell",

    // User Profile
    userProfileTitle: "User Profile",
    editProfile: "Edit Profile",
    accountVerified: "Account Verified",
    saveChanges: "Save Changes",
    cancelEdit: "Cancel",
    fullNameLabel: "Full Name",
    locationLabel: "Location",
};

const knStrings = {
    ...enStrings, // Fallback for any missing strings
    landing_top_bar: "ಆಧುನಿಕ ಕೃಷಿಗಾಗಿ AI-ಚಾಲಿತ ಪರಿಹಾರಗಳು.",
    landing_nav_home: "ಮುಖಪುಟ",
    landing_nav_about: "ನಮ್ಮ ಬಗ್ಗೆ",
    landing_nav_services: "ವೈಶಿಷ್ಟ್ಯಗಳು",
    landing_nav_contact: "ಸಂಪರ್ಕಿಸಿ",
    landing_hero_tagline: "ಕೃಷಿಯ ಭವಿಷ್ಯ ಇಲ್ಲಿದೆ",
    landing_hero_title: "ತಂತ್ರಜ್ಞಾನದೊಂದಿಗೆ ಆರೋಗ್ಯವನ್ನು ನಿರ್ಮಿಸಿ",
    landing_hero_subtitle: "ಕರ್ನಾಟಕದಾದ್ಯಂತ ರೈತರಿಗೆ ಉತ್ತಮ ಕೃಷಿ ಪರಿಹಾರಗಳನ್ನು ಒದಗಿಸಲು AI ಅನ್ನು ಬಳಸುವುದು.",
    landing_cta_dashboard: "AI ಸಹಾಯಕ",
    landing_cta_learn_more: "ಇನ್ನಷ್ಟು ತಿಳಿಯಿರಿ",
    landing_features_title: "ನಮ್ಮ ವೈಶಿಷ್ಟ್ಯಗಳು",
    landing_features_subtitle: "ಆಧುನಿಕ ಕೃಷಿಗಾಗಿ ನಾವು ನಿಮ್ಮ ಉತ್ತಮ ಪಾಲುದಾರ",
    landing_feature1_title: "ಸ್ಥಳೀಯ ಹವಾಮಾನ ಮುನ್ಸೂಚನೆ",
    landing_feature1_desc: "ನಿಮ್ಮ ನಿರ್ದಿಷ್ಟ ಜಿಲ್ಲೆಗೆ ಹೈಪರ್ಲೋಕಲ್, ನೈಜ-ಸಮಯದ ಹವಾಮಾನ ನವೀಕರಣಗಳನ್ನು ಪಡೆಯಿರಿ.",
    landing_feature2_title: "AI ಮಣ್ಣು ವಿಶ್ಲೇಷಣೆ",
    landing_feature2_desc: "ನಿಮ್ಮ ಮಣ್ಣಿನ ಆರೋಗ್ಯ ಮತ್ತು ಸ್ಥಳೀಯ ಪರಿಸ್ಥಿತಿಗಳ ಆಧಾರದ ಮೇಲೆ ನೈಜ-ಸಮಯದ ಬೆಳೆ ಶಿಫಾರಸುಗಳನ್ನು ಪಡೆಯಿರಿ.",
    landing_feature3_title: "ಭೂಮಿ AI ಸಹಾಯಕ",
    landing_feature3_desc: "ಎಲ್ಲಾ ಕೃಷಿ-ಸಂಬಂಧಿತ ಪ್ರಶ್ನೆಗಳಿಗೆ ನಿಮ್ಮ ದ್ವಿಭಾಷಾ AI ಸಹಾಯಕ.",
    landing_feature4_title: "ಸಸ್ಯ ರೋಗ ವಿಶ್ಲೇಷಣೆ",
    landing_feature4_desc: "ಸಸ್ಯದ ಚಿತ್ರವನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಿ, ತಕ್ಷಣದ AI-ಚಾಲಿತ ರೋಗನಿರ್ಣಯ ಮತ್ತು ಚಿಕಿತ್ಸಾ ಯೋಜನೆಯನ್ನು ಪಡೆಯಿರಿ.",
    landing_feature5_title: "ಕೃಷಿ-ಮಾರುಕಟ್ಟೆ",
    landing_feature5_desc: "ನೈಜ-ಸಮಯದ ಮಾರುಕಟ್ಟೆ ಬೆಲೆಗಳನ್ನು ವಿಶ್ಲೇಷಿಸಿ, ಮಾರುಕಟ್ಟೆಗಳಾದ್ಯಂತ ಹೋಲಿಕೆ ಮಾಡಿ ಮತ್ತು ನಿಮ್ಮ ಉತ್ಪನ್ನಕ್ಕೆ ಉತ್ತಮ ಮೌಲ್ಯವನ್ನು ಪಡೆಯಿರಿ.",
    why_choose_us_title: "ಅಗ್ರಿವರ್ಸ್ಎಐ ಏಕೆ ಆಯ್ಕೆ ಮಾಡಬೇಕು?",
    why_choose_us_1_title: "ಡೇಟಾ-ಚಾಲಿತ ಒಳನೋಟಗಳು",
    why_choose_us_1_desc: "ಮಣ್ಣು, ಹವಾಮಾನ ಮತ್ತು ಬೆಳೆ ಆರೋಗ್ಯದ ನಿಖರವಾದ ಡೇಟಾದೊಂದಿಗೆ ತಿಳುವಳಿಕೆಯುಳ್ಳ ನಿರ್ಧಾರಗಳನ್ನು ತೆಗೆದುಕೊಳ್ಳಿ.",
    why_choose_us_2_title: "ದ್ವಿಭಾಷಾ AI ಬೆಂಬಲ",
    why_choose_us_2_desc: "ಇಂಗ್ಲಿಷ್ ಮತ್ತು ಕನ್ನಡ ಎರಡರಲ್ಲೂ ತಜ್ಞರ ಸಲಹೆ ಪಡೆಯಿರಿ, ಎಲ್ಲರಿಗೂ ಪ್ರವೇಶಿಸಬಹುದು.",
    why_choose_us_3_title: "ಆಲ್-ಇನ್-ಒನ್ ಪ್ಲಾಟ್‌ಫಾರ್ಮ್",
    why_choose_us_3_desc: "ರೋಗನಿರ್ಣಯದಿಂದ ಮಾರುಕಟ್ಟೆ ಮಾಹಿತಿಯವರೆಗೆ, ನಿಮಗೆ ಬೇಕಾದ ಎಲ್ಲಾ ಪರಿಕರಗಳು ಒಂದೇ ಸ್ಥಳದಲ್ಲಿ.",

    appName: "ಅಗ್ರಿವರ್ಸ್ಎಐ",
    appDescription: "ನಿಮ್ಮ AI-ಚಾಲಿತ ಕೃಷಿ ಪಾಲುದಾರ.",
    languageKN: "ಕನ್ನಡ",
    cancel: "ರದ್ದುಮಾಡಿ",

    assistantWelcome: "ನಮಸ್ಕಾರ! 👋 ನಾನು ಭೂಮಿ, ನಿಮ್ಮ ಆತ್ಮೀಯ AI ಕೃಷಿ ಸ್ನೇಹಿತೆ! ಬೆಳೆಗಳು, ಮಣ್ಣಿನ ಆರೋಗ್ಯ, ಮಾರುಕಟ್ಟೆ ಬೆಲೆಗಳು ಮತ್ತು ಇನ್ನಷ್ಟು ವಿಷಯಗಳಲ್ಲಿ ನಿಮಗೆ ಸಹಾಯ ಮಾಡಲು ನಾನು ಇಲ್ಲಿದ್ದೇನೆ. ನನ್ನನ್ನು ನಿಮ್ಮ ಕೃಷಿ ಅಕ್ಕ ಎಂದು ತಿಳಿಯಿರಿ! 🌾💚",
    askWithVoice: "ನಿಮ್ಮ ಧ್ವನಿಯೊಂದಿಗೆ ಕೇಳಿ",
    typeWithKeyboard: "ನಿಮ್ಮ ಕೀಬೋರ್ಡ್ ಬಳಸಿ ಟೈಪ್ ಮಾಡಿ",
    bilingualSupport: "ತಡೆರಹಿತ ಸಂಭಾಷಣೆಗಳಿಗಾಗಿ ದ್ವಿಭಾಷಾ ಬೆಂಬಲ.",
    examplePromptsTitle: "ನೀವು ನನ್ನನ್ನು ಏನು ಕೇಳಬಹುದು:",
    getStarted: "ಪ್ರಾರಂಭಿಸಿ",
    exampleCategories: [
        { title: "ಬೆಳೆ ಸಲಹೆ", prompts: [{ text: "ಹೆಚ್ಚು ಪೊಟ್ಯಾಸಿಯಮ್ ಇರುವ ಕೆಂಪು ಮಣ್ಣಿನಲ್ಲಿ ಬೆಳೆಯಲು ಉತ್ತಮ ಬೆಳೆಗಳು ಯಾವುವು?" }] },
        { title: "ರೋಗ ನಿರ್ಣಯ", prompts: [{ text: "ನನ್ನ ಟೊಮೆಟೊ ಗಿಡದ ಎಲೆಗಳಲ್ಲಿ ಹಳದಿ ಕಲೆಗಳಿವೆ. ಅದು ಏನಾಗಿರಬಹುದು?" }] },
        { title: "ಮಾರುಕಟ್ಟೆ ಬೆಲೆಗಳು", prompts: [{ text: "ಬೆಳಗಾವಿ ಜಿಲ್ಲೆಯಲ್ಲಿ ಈರುಳ್ಳಿಯ ಪ್ರಸ್ತುತ ಮಾರುಕಟ್ಟೆ ಬೆಲೆ ಎಷ್ಟು?" }] },
        { title: "ಯೋಜನೆಯ ಮಾಹಿತಿ", prompts: [{ text: "ಪಿಎಂ-ಕಿಸಾನ್ ಯೋಜನೆ ಬಗ್ಗೆ ಹೇಳಿ." }] }
    ] as ExampleCategory[],
    messagePlaceholder: "ಹಾಯ್ ಭೂಮಿ! ನನಗೊಂದು ಪ್ರಶ್ನೆ ಇದೆ... 🌱",
    send: "ಕಳುಹಿಸು",
    voiceOutput: "ಧ್ವನಿ ಔಟ್ಪುಟ್ ಟಾಗಲ್ ಮಾಡಿ",
    cancelVoiceOutput: "ಧ್ವನಿ ಔಟ್ಪುಟ್ ರದ್ದುಮಾಡಿ",
    errorPrefix: "ದೋಷ:",
    errorApiGeneric: "ಕ್ಷಮಿಸಿ, ನನ್ನ ಜ್ಞಾನದ ಮೂಲಕ್ಕೆ ಸಂಪರ್ಕಿಸಲು ನನಗೆ ತೊಂದರೆಯಾಗುತ್ತಿದೆ. ದಯವಿಟ್ಟು ನಂತರ ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.",
    errorSpeechNetwork: "ನೆಟ್‌ವರ್ಕ್ ಸಮಸ್ಯೆಯಿಂದಾಗಿ ಧ್ವನಿ ಗುರುತಿಸುವಿಕೆ ವಿಫಲವಾಗಿದೆ. ದಯವಿಟ್ಟು ನಿಮ್ಮ ಸಂಪರ್ಕವನ್ನು ಪರಿಶೀಲಿಸಿ.",
    errorSpeechGeneric: "ಕ್ಷಮಿಸಿ, ನನಗೆ ಅದನ್ನು ಅರ್ಥಮಾಡಿಕೊಳ್ಳಲು ಸಾಧ್ಯವಾಗಲಿಲ್ಲ. ದಯವಿಟ್ಟು ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.",
    attachFile: "ಫೈಲ್ ಲಗತ್ತಿಸಿ",
    agriculturalFacts: [
        "ಒಂದು ಬುಶೆಲ್ ಗೋಧಿಯಲ್ಲಿ ಸುಮಾರು ಒಂದು ಮಿಲಿಯನ್ ಪ್ರತ್ಯೇಕ ಕಾಳುಗಳಿವೆ.",
        "ಹೈಡ್ರೋಪೋನಿಕ್ಸ್, ನೀರಿನ ದ್ರಾವಣದಲ್ಲಿ ಖನಿಜ ಪೋಷಕಾಂಶಗಳನ್ನು ಬಳಸಿ, ಮಣ್ಣಿಲ್ಲದೆ ಸಸ್ಯಗಳನ್ನು ಬೆಳೆಸಲು ಅನುವು ಮಾಡಿಕೊಡುತ್ತದೆ.",
        "ಜೇನುನೊಣಗಳು ಕೃಷಿಗೆ ನಿರ್ಣಾಯಕ, ಸುಮಾರು 80% ಹೂಬಿಡುವ ಸಸ್ಯಗಳನ್ನು ಪರಾಗಸ್ಪರ್ಶ ಮಾಡುತ್ತವೆ.",
        "ವಿಶ್ವದ ಅತ್ಯಂತ ಹಳೆಯ ಜೀವಂತ ಮರ, ಮೆಥುಸೆಲಾ, 4,850 ವರ್ಷಗಳಿಗಿಂತ ಹೆಚ್ಚು ಹಳೆಯದು."
    ],
    listening: "ಮುಂದುವರಿಸಿ, ನಾನು ಕೇಳುತ್ತಿದ್ದೇನೆ",

    plantAnalysisTitle: "ಎಐ ಸಸ್ಯ ರೋಗ ವಿಶ್ಲೇಷಣೆ",
    plantAnalysisDescription: "ತ್ವರಿತ, ಅನಿಮೇಟೆಡ್ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್ ವಿಶ್ಲೇಷಣೆ ಪಡೆಯಲು ಪೀಡಿತ ಸಸ್ಯದ ಸ್ಪಷ್ಟ ಫೋಟೋವನ್ನು ಸೆರೆಹಿಡಿಯಿರಿ ಅಥವಾ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ.",
    uploadPlantImagePrompt: "ಚಿತ್ರವನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಲು ಕ್ಲಿಕ್ ಮಾಡಿ ಅಥವಾ ಎಳೆದು ಬಿಡಿ",
    analyzingPlant: "ನಿಮ್ಮ ಸಸ್ಯವನ್ನು ವಿಶ್ಲೇಷಿಸಲಾಗುತ್ತಿದೆ...",
    analysisResults: "ವಿಶ್ಲೇಷಣೆ ಫಲಿತಾಂಶಗಳ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
    diseaseName: "ರೋಗದ ಹೆಸರು",
    confidence: "ವಿಶ್ವಾಸ",
    description: "ವಿವರಣೆ",
    severity: "ತೀವ್ರತೆ",
    symptoms: "ರೋಗಲಕ್ಷಣಗಳು",
    prevention: "ತಡೆಗಟ್ಟುವಿಕೆ",
    treatment: "ಚಿಕಿತ್ಸೆ",
    medicineName: "ಶಿಫಾರಸು ಮಾಡಿದ ಔಷಧಿ",
    usageInstructions: "ಬಳಕೆಯ ಸೂಚನೆಗಳು",
    healthyPlant: "ಸಸ್ಯವು ಆರೋಗ್ಯಕರವಾಗಿ ಕಾಣುತ್ತದೆ",
    healthyPlantDesc: "ಒದಗಿಸಿದ ಚಿತ್ರದಲ್ಲಿ ಯಾವುದೇ ರೋಗ ಪತ್ತೆಯಾಗಿಲ್ಲ. ನಿಮ್ಮ ಸಸ್ಯವನ್ನು ಚೆನ್ನಾಗಿ ನೋಡಿಕೊಳ್ಳುವುದನ್ನು ಮುಂದುವರಿಸಿ.",
    errorAnalysis: "ಚಿತ್ರವನ್ನು ವಿಶ್ಲೇಷಿಸಲು ಸಾಧ್ಯವಾಗಲಿಲ್ಲ. ದಯವಿಟ್ಟು ಸ್ಪಷ್ಟವಾದ ಚಿತ್ರದೊಂದಿಗೆ ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.",
    analyzeAnotherPlant: "ಮತ್ತೊಂದು ಸಸ್ಯವನ್ನು ವಿಶ್ಲೇಷಿಸಿ",
    captureWithCamera: "ಕ್ಯಾಮೆರಾದೊಂದಿಗೆ ಸೆರೆಹಿಡಿಯಿರಿ",
    or: "ಅಥವಾ",
    switchCamera: "ಕ್ಯಾಮೆರಾ ಬದಲಿಸಿ",
    capture: "ಸೆರೆಹಿಡಿಯಿರಿ",
    retake: "ಮತ್ತೆ ತೆಗೆ",
    usePhoto: "ಫೋಟೋ ಬಳಸಿ",
    downloadReport: "ವರದಿ ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ",
    readAloud: "ಗಟ್ಟಿಯಾಗಿ ಓದಿ",
    stopReading: "ಓದುವುದನ್ನು ನಿಲ್ಲಿಸಿ",
    topDetections: "ಪ್ರಮುಖ ಪತ್ತೆಗಳು",
    affectedArea: "ಪೀಡಿತ",
    healthyArea: "ಆರೋಗ್ಯಕರ",
    riskFactors: "ಅಪಾಯಕಾರಿ ಅಂಶಗಳು",
    historicalData: "ಐತಿಹಾಸಿಕ ಪತ್ತೆಗಳು (ಮಾದರಿ)",
    viewHealthDashboard: "ಪ್ರಾದೇಶಿಕ ಆರೋಗ್ಯ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್ ವೀಕ್ಷಿಸಿ",
    backToAnalysis: "ವಿಶ್ಲೇಷಣೆಗೆ ಹಿಂತಿರುಗಿ",
    plantHealthDashboardTitle: "ರಾಜ್ಯವ್ಯಾಪಿ ಸಸ್ಯ ಆರೋಗ್ಯ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
    keyMetrics: "ಪ್ರಮುಖ ಮೆಟ್ರಿಕ್‌ಗಳು",
    totalDetections: "ಒಟ್ಟು ಪತ್ತೆಗಳು",
    activeAlerts: "ಸಕ್ರಿಯ ಎಚ್ಚರಿಕೆಗಳು",
    cropsAffected: "ಬೆಳೆಗಳು ಬಾಧಿತವಾಗಿವೆ",
    diseaseSeverityIndex: "ರೋಗ ತೀವ್ರತೆ ಸೂಚ್ಯಂಕ",
    diseaseTrend: "ರೋಗದ ಪ್ರವೃತ್ತಿ (12 ತಿಂಗಳುಗಳು)",
    detections: "ಪತ್ತೆಗಳು",
    cropDistribution: "ಬೆಳೆ ವಿತರಣೆ",
    diseaseDistribution: "ರೋಗ ವಿತರಣೆ",
    environmentalCorrelation: "ಪರಿಸರ ಸಂಬಂಧ",
    mostAffectedDistricts: "ಹೆಚ್ಚು ಪೀಡಿತ ಜಿಲ್ಲೆಗಳು",
    cropDiseaseHotspots: "ಬೆಳೆ-ರೋಗದ ಪ್ರಮುಖ ಕೇಂದ್ರಗಳು",
    crop: "ಬೆಳೆ",
    disease: "ರೋಗ",
    priorityAlertsTitle: "ರಾಜ್ಯವ್ಯಾಪಿ ಆದ್ಯತೆಯ ಎಚ್ಚರಿಕೆಗಳು",
    riskLevel: "ಅಪಾಯದ ಮಟ್ಟ",
    highRisk: "ಹೆಚ್ಚು",
    moderateRisk: "ಮಧ್ಯಮ",
    lowRisk: "ಕಡಿಮೆ",
    affectedRegions: "ಹೆಚ್ಚು ಅಪಾಯದ ಪ್ರದೇಶಗಳು",
    recommendedAction: "ಶಿಫಾರಸು ಮಾಡಿದ ಪ್ರಾಥಮಿಕ ಕ್ರಮ",
};


export const uiStrings: UIStrings = {
    [Language.EN]: enStrings,
    [Language.KN]: knStrings,
};